### ISSUE TITLE
@tag/list fixes/improvements

### ISSUE THREAD

**Issue by warmstarter** [RhostMUSH/trunk#126]
With @tag I found both some undocumented, slightly odd behavior, and some missing features that might be expected. Since this exists in hardcode already, I thought it might make sense to mention these things and see what your thoughts are on the matter.

At the same time, the available softcode tag-related functions make writing a softcode replacement pretty straightforward, so don't worry too much on this if any of it is a pain.

I figure at the least though, the undocumented hardcode stuff should get documented. I'm happy to help on that, but I figured I should get an understanding of the oddities before attempting such.

I current have have 3 pages worth of tags that will show up in @tag/list and there are a few awkward bits to it.

The commands to view are a bit odd:

This shows page 1: @tag/list 
This shows page 2: @tag/list 1
This shows page 3: @tag/list 2
This also shows page 3: @tag/list 3
These also show page 3: @tag/list <any number above 3>

I'm not sure if there's any reason for that ordering. It seems like it would make more send for @tag/list and @tag/list 1 to both show 1; @tag/list 2 to show 2; @tag/list 3 to show 3; and @tag/list <number above 3> to perhaps error?

Also the ability to do this page based listing isn't even documented. Even though it works and seems like a logical thing to do to, the help only mentions @tag/list <searchstring>

There are duplicates that appear:

When looking at page 2, the first listed tag is the last listed tag of page 1, and the last listed tag of page 2 is the first listed tag of page 3. I can't think of any reason why this is useful, but maybe I'm missing something.

Ordering:

While things seem to appear in the same order each time, there doesn't seem to be any logic to that order.

1) It would be really nice to be able to have the returned tag list sorted alphabetically.

2) It would also be nice to have the option to instead have it sorted by dbref#. 

3) Rearranging the column order would also be very handy.

**Comment by mrsenile** [comment]
All the issues should be fixed.
@tag/list 0 will list all the tags (un-paged)
@tag/list 1 will list page 1, 2 page 2, and so forth
If you have 10 pages, anything above '10' will show page 10.

Duplicates should no longer appear.  It was a one off in paging.

Sorting will be fairly impossible because of potential overhead.  The fact that tags can have more or less an unlimited number, sorting would require setting up an array of equal to the number of tags, so something that uses a stupid number of tags could potentially resource starve the stack for something that has little benefit.  Tags are currently ordered in the order they were added as they're hashed.
