### ISSUE TITLE
Feature Request: @dolist and %i0

### ISSUE THREAD

**Issue by HarryCordewener** [RhostMUSH/trunk#13]
The request is obvious from the title:
Bring %i0 etc replacements to @dolist so it can be safer. (For non-inline)

**Comment by mrsenile** [comment]
Making %d0-%dx (like @dolist/inline can do) is going to be a major pain in the ass to do cleanly and successfully and require a large overhead for frankly minimal gains.

The /inline was much easier as it didn't require queueing the stack up for each iteration of @dolist.  This however would.

**Comment by mrsenile** [comment]
Looking more at the code, as of right now it would be nearly 2 meg of overhead per calling stack to make @dolist (without the /inline) handle %d (your %i#).  This would be again, per calling stack, which is a huge huge huge overhead on something very few people would likely do.

If you want to use the %d with @dolist, I suggest using the /inline switch, otherwise use of ## is the only option.
