### ISSUE TITLE
MUSHQN_ not being populated

### ISSUE THREAD

**Issue by CuAnnan** [RhostMUSH/trunk#146]
&cmd.feeding.setPool zobj=$+feed/pool  *:[setq(user, %#)];[setq(pool, %0)];[setq(res, [execscript([u(con.domain.path)], setFeedingPool, [objid(%#)]|[%0])])];@sudo %l=@pemit [r(user)]=[r(res)]

MUSHQ_U and MUSHQ_N both show up but not the MUSHQN_ or MUSHN_ variables.

**Comment by mrsenile** [comment]
Please verify that the register you are using is alphanumerical and does not contain special characters or spaces.

It will still 'work for normal numerical register, but because of how the backend system works in passing the values as shell variables, you are limited in what characters shell variables see as valid, which in this case is alphanumerical (without white spaces).

Please let us know if you used l;pahnumerical or special characters and/or spaces.

**Comment by CuAnnan** [comment]
It is alphanumerical, does not contain characters or spaces. It's the word user. But no words are being populated.

**Comment by CuAnnan** [comment]
Ubuntu 20.04 OS

**Comment by mrsenile** [comment]
`
$ cat setq.sh
#!/bin/bash
echo "MUSH Stuff"
echo "MUSHQ_0: ${MUSHQ_0}"
echo "MUSHQN_0: ${MUSHQN_0}"
echo "MUSHN_USER: ${MUSHN_USER}"
`

`
> think [setq(0,how now brown cow,user)][execscript(setq.sh)]

MUSH Stuff
MUSHQ_0: how now brown cow
MUSHQN_0: user
MUSHN_USER: how now brown cow
`

Works fine to me.  Make sure the variables are all upper case.

**Comment by stevensmedia** [comment]
Weird it is now working for me now, though it wasn't before.

**Comment by CuAnnan** [comment]
I am not using the syntax setq(<#>, val, <string>).
I am using the syntax setq(<string>, val)
Does only the former work?

**Comment by CuAnnan** [comment]
And, again. No musqn variable is present.

**Comment by CuAnnan** [comment]
https://raw.githubusercontent.com/CuAnnan/domain/main/output.txt

Both the command on the object in question and the raw output
