### ISSUE TITLE
@cluste/rclone

### ISSUE THREAD

**Issue by g33kcub** [RhostMUSH/trunk#17]
A way to clone a cluster. Without having to manually clone each object and recreating a new cluster.

**Comment by mrsenile** [comment]
Cloning a cluster is too easy to do in softcode.

$@clonecluster *:@assert [t(cluster_stats(%0,0)]=@pemit %#=Not a cluster;@dolist/inline cluster_stats(%0,1)={@eval [setq(0,cat(%q0,setr(1,create(Cluster #@))))];@sw/inline #@=1,{@cluster/new [setr(2,%q1)];@cpattr ##/*=%q1},{@cluster/add %q1=%q2;@cpattr ##/*=%q1}

Due to the ease of softcoding this, going to close it as 'not needed'.
