### ISSUE TITLE
Newpass changed by who?

### ISSUE THREAD

**Issue by Eckspert** [RhostMUSH/trunk#49]
When I reset #1's password with @newpass, it failed to report who... Below is what I see.

Your password has been changed by .

**Comment by mrsenile** [comment]
Per the code the only time this would occur is if the name of the player was literally blank.

For example, the db that gets loaded is corrupt and all the names are gone.
You log in #1 with the newpass_god setting, then @newpassword me=foo

That will tell you the name is 'empty' because with the corrupt db the name would be empty.

Can you please verify the name of the player at the time when you newpassworded #1?

**Comment by Eckspert** [comment]
The DB had infact corrupted
