### ISSUE TITLE
Question regarding the version of RHostMUSH

### ISSUE THREAD

**Issue by mdziczkowski** [RhostMUSH/trunk#83]
Hello. I wanted to ask about, on with version of Tiny are based the versions of 3.9 and 4.0 from RHost ?

**Comment by Chalice** [comment]
Rhost is, originally, based on TinyMUD.

Over time, Rhost took on features of TinyMUSH, MUX, MUSE, MUCK, LP, DIKU and PennMUSH.

It is not directly based on any TinyMUSH version, however it is a mostly compatible, full MUSH server these days, instead of anything like a MUD.

**Comment by mdziczkowski** [comment]
@Chalice You had missread my question. I asked about the version on with are they based and not about what kind if Tiny ;-p

**Comment by mrsenile** [comment]
Ambrosia essentially answered you.

RhostMUSH is based on TinyMUD 1.0.

It inherited compatibility (85-95% depending on the feature) to PennMUSH 1.8.6+, MUX 2.12+, TinyMUSH 3.2+, Some LambdaMOO (non-version), some TinyMUCK (nonversion), TinyMUSE 1.6+, and some LPMud (non-version), and Diku (non-version) sprinkled in.

Most code written for MUX, TinyMUSH2, TinyMUSH3 should work in Rhost with minimal changes.

PennMUSH may or may not work with more or less changes because their parser is radically different under the hood than other mush flavors.  PennMUSH doesn't care about ending braces, brackets, and parenthesis, all other mush codebases do.

Hope that helps.

**Comment by Chalice** [comment]
Also, on a note, if you have questions and want to talk more interactively, we have a Discord running at https://discord.gg/WmyxpN6w

**Comment by mdziczkowski** [comment]
@mrsenile Thanks. Shame only that it's based on such old and outdated version of TinyMUD (as I saw, on GitHub the latest version of it is (as I remember) 3.2.

Wouldn't be a good idea to update the base to get the latest features in, with weren't there in version 1.0 ?

**Comment by Chalice** [comment]
I think you are confusing things a bit :)

TinyMUD isn't TinyMUSH. 

RhostMUSH started in 1989 as a TinyMUD 1.0 derivative, and it was a MUD server at the time - but over the decades that have passed, it has has changed a lot, and has become a full fledged MUSH Server. RhostMUSH is its own codebase by now, there is nothing to rebase it on.

It offers a lot more features than TinyMUSH 3.2 and is mostly compatible with most MUSH servers out there in terms of in-game MUSHcode - including PennMUSH, MUX and TinyMUSH.

**Comment by mrsenile** [comment]
If it helps make sense, TinyMUD was the ancestor of all MUSH's currently existing.  Rhost was around before TinyMUSH was even a thing.

**Comment by mrsenile** [comment]
I'm closing this.

To further express how we don't need to 'upgrade' to TinyMUSH...

TinyMUSH 3.3 -- 417 built in functions
TinyMUX 2.12 -- 350 built in functions
RhostMUSH 4.2 -- 584 built in functions.

'upgrading' to TinyMUSH 3.3 would be regressing several years of new features to a far less feature-rich codebase.
