### ISSUE TITLE
AshScan SoftCode Feature Request

### ISSUE THREAD

**Issue by warmstarter** [RhostMUSH/trunk#89]
I think others might find this idea helpful, though unfortunately is a bit beyond my abilities at the moment. I promise though that I will contribute as much as I can to RhostMUSH in the area my abilities allow for!

Basically sometimes you want to disable a command, perhaps to test a new version, perhaps you uploaded code and don't want all of it, but want to keep it around, a whole lot of things.

Currently AshScan searches for commands, which are attributes that have content that starts with '$'

It would be really nice if it could also search for attribute content that starts with '@@ $' and gives the same detail about it though noting it's disabled.

It would potentially be nice to add to AshScan a command disabled/enable feature, basically it could allow you to transform that beginning '@@ $' back to a '$' or a beginning '$' to a '@@ $' I can already do that very easily via my client, so not something I desperately need, just seems like interesting and related functionality.

**Comment by mrsenile** [comment]
This is effectively already there.  If you set the command NO_COMMAND (@set #obj/attr=no_command) it will still show the command on searches but show *LK* beside it (locked command) to let you know it's currently disabled.

I could also add '@@' but I find it counter productive since just setting the attribute no_command solves the issue.
